import Head from "next/head";
import Hero from "../components/Hero";
import About from "../components/About";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Artsem Shauchuk Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero
        heading="Web Applications Developer"
        message="Inspire. Develop. Enjoy."
      />
      <About />
    </div>
  );
}
